### ISSUE TITLE
镜像的密码？

### ISSUE THREAD

**Issue by Hatcat123** [lujinzhong/Live_basketball_room#1]
似乎登录不了xiaolu用户，大佬，能提供一下密码吗？

**Comment by lujinzhong** [comment]
I am sorry, the passwod may be '960801' or 'Lu960801' ，you can have a try

**Comment by Hatcat123** [comment]
感谢你的密码，但是似乎会泄露你的一些关于个人身份信息，你也可以删掉个iss
